### ISSUE TITLE
Restructure program into modules?

### ISSUE THREAD

**Issue by brendanashworth** [debugger22/Jarvis#10]
Hi there;

Just looking at the project seemed pretty cool so I thought I could help. I think that if the project was restructured into some sort of module setup it would help developing more features for Jarvis and it would also help eliminate an issue down the road.

Currently, the program seems to be haphazardly put into the `src` directory and directories inside it. There is a Jarvis sort of home in the `/` directory, and the `src/brain.py` is in the same directory as the text to speech, speech to text, network and wikipedia files.

In my opinion, I think that the `brain.py` and files like it should be kept inside the home `src` folder, and there should be a `modules` folder inside `src` that will keep all the modules in an organized and easy way of keeping them at hand.

There can also be an abstract Python class that each module extends, which will allow for even better structure.

Its okay if you don't agree with the changes I think should be made, its understandable, especially since I'm just jumping in. :)

**Comment by jyotiska** [comment]
+1

Lets put all the files in the <code>src</code> folder as classes in a single file, which will be easy to extend/add other features.

**Comment by srizzling** [comment]
Yeah I agree to this. I quite like the structure displayed here https://github.com/jasperproject/jasper-client

**Comment by brendanashworth** [comment]
I'm going to formulate a pull request for this sometime before/during the weekend and submit it. Hopefully it'll allow easier expansion in the future :+1:

**Comment by srizzling** [comment]
Ok. How are you planning to abstract each "module"?

**Comment by brendanashworth** [comment]
@srizzling, I'm thinking the best way would to have an abstract base class that each module can extend, with each file acting as its own module (with one class per module).

**Edit:** I might also look into doing it how jasperproject/jasper-client does it, that seems like a very simple and easy solution.

**Comment by jyotiska** [comment]
+1 for reference to Jasper. I agree that we have to do something similar. Create a base class and extend it for every module.

**Comment by brendanashworth** [comment]
It doesn't look like this project is maintained, closing.
