### ISSUE TITLE
FEATURE: What is the time?

### ISSUE THREAD

**Issue by srizzling** [debugger22/Jarvis#6]
A feautre I might add to this is the ability for to find out time. I'll make a PR for it as soon I learn the structure of the program...

**Comment by debugger22** [comment]
Yeah that's a very good thing to have.

**Comment by srizzling** [comment]
Given I add this feature it would be nice if we could have some sort of regex natural language parsing in the application. Would be nice for future additions and development. Not entierly sure of any natural language parsing in Python. I can see the for loop getting ridiculously large at some point

**Comment by debugger22** [comment]
@srizzling You can close issues with commit messages. See [this](https://help.github.com/articles/closing-issues-via-commit-messages).

**Comment by srizzling** [comment]
Oh! Useful feature thanks!
